config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'business', to: 'pages#business'
  get 'hosts', to: 'pages#hosts'
  get 'membership', to: 'pages#membership'
  get 'privacy', to: 'pages#privacy'
  get 'support', to: 'pages#support'
  get 'guidelines', to: 'pages#guidelines'
  get 'terms', to: 'pages#terms'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index] do
    member do
      post :accept
      post :reject
    end
  end

  resources :workspaces do
    resources :bookings, only: [:new, :create, :edit, :update]
    resources :favorites, only: [:index, :create, :destroy]
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  validates :name, :description, :capacity, :price, :city, :postcode, presence: true
  validates :terms_of_service, acceptance: true
  validates :name, length: 5..28

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :workspace_amenities, dependent: :destroy
  has_many :amenities, through: :workspace_amenities, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :photos
  geocoded_by :postcode
  after_validation :geocode, if: :will_save_change_to_postcode?

  include PgSearch::Model
  pg_search_scope :search_by_location,
  against: [ :city, :postcode ],
      using: {
        tsearch: { prefix: true }
    }

  def average
    reviews.average(:rating).to_f.round(1)
  end
  # use regex to return first half of postcode for show page
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    @workspaces = Workspace.all
    if params.dig(:index_search, :search_city).present? && params.dig(:index_search, :search_distance).present?
      @workspaces = @workspaces.near(params.dig(:index_search, :search_city), params.dig(:index_search, :search_distance), units: :km)
      if @workspaces.empty?
        @workspaces = Workspace.search_by_location(params.dig(:index_search, :search_city))
      end
    end

    amenities = params.dig(:index_search, :amenities)&.reject { |amenity| amenity.blank? }
    if amenities && amenities.length > 0
      @workspaces = @workspaces.joins(workspace_amenities: :amenity).where(workspace_amenities: { amenities: { name: amenities } })
    end

    @markers = @workspaces.geocoded.map do |workspace|
      {
        lat: workspace.latitude,
        lng: workspace.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { workspace: workspace })
      }
    end
  end

  def show
    @workspace = Workspace.find(params[:id])
    @marker = [{
        lat: @workspace.latitude,
        lng: @workspace.longitude
      }]
  end

  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.create(strong_params)
    @workspace.user = current_user
    if @workspace.save
      flash[:notice] = "#{@workspace.name} has been created!"
      redirect_to workspace_path(@workspace)
    else
      render :new
    end
  end

  def edit
    @workspace = Workspace.find(params[:id])
  end

  def update
    @workspace = Workspace.find(params[:id])
    if @workspace.update(strong_params)
      redirect_to workspace_path(@workspace)
    else
      render :edit
    end
  end

  def destroy
    @workspace = Workspace.find(params[:id])
    @workspace.destroy
    redirect_to workspaces_path
  end

  private

  def strong_params
    params.require(:workspace).permit(:name, :description, :capacity, :price, :first_line_address, :city, :postcode, photos: [], amenity_ids: [])
  end
end

app/views/workspaces/_info_window.html.erb
<div class="map-icons">
  <h2><%= workspace.name %></h2>
  <p><%= workspace.postcode %></p>
</div>

app/views/workspaces/_searchbar.html.erb
<div class="index-form form-inline justify-content-center m-3">
  <%= form_tag workspaces_path, :method => "get" do %>
    <%= text_field_tag :search_city, params[:search_city], class: "form-control rounded-left", placeholder: "London" %>
    <%= text_field_tag :search_distance, params[:search_distance], class: "form-control", placeholder: "Within 5 miles" %>
    <%= submit_tag "Search", class: "btn btn-primary"  %>
  <% end %>
</div>

app/views/workspaces/edit.html.erb
<div class="container" style="width: 500px">
  <div class="form-container">
    <h2>Edit your space</h2>
    <div class="form-inputs">
        <%= simple_form_for @workspace do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :first_line_address %>
        <%= f.input :city %>
        <%= f.input :postcode %>
        <%= f.association :amenities,
                                  collection: Amenity.all, as: :check_boxes,
                                  wrapper: :vertical_collection_inline,
                                  input_html: { class: "tag-selector" },
                                  item_wrapper_class: 'tag-item'%>
        <%= f.input :photos, as: :file, input_html: { multiple: true }%>
      <div class="form-actions">
        <%= f.submit "Edit Workspace", class:"btn btn-warning" %>
        <%= link_to 'Back', workspaces_path, class: "btn btn-info"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/workspaces/index.html.erb
<div class="workspaces">
  <div class="workspaces-leftside">
    <div class="filter-form">
      <%= simple_form_for :index_search, url: workspaces_path, method: :get, html: { class: 'w-100' } do |f| %>
      <div class="filter-flex">
        <div class="filter-left">
          <div class="form-top">
            <%= f.input :search_city, class: "form-control rounded-left", placeholder: "Area or Postcode", label: false %>
            <%= f.input :search_distance, class: "form-control", placeholder: "Km radius", label: false  %>
          </div>
        </div>
        <%= f.submit "Search", class: "btn btn-warning"%>
      </div>
    <% end %>
    </div>
    <div class="workspaces-cards">
      <% @workspaces.each do |workspace| %>
      <%= link_to workspace_path(workspace), class: "workspace-link" do %>
      <div class="workspace-card">
        <% if workspace.photos.attached? %>
          <%= cl_image_tag workspace.photos.first.key, class: "img" %>
        <% else %>
          <img class="card-image-workspace" src="https://images.unsplash.com/photo-1519974719765-e6559eac2575?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTAyfHxob21lJTIwb2ZmaWNlfGVufDB8fDB8&auto=format&fit=crop&w=500&q=60" alt="airy desk in bedroom">
        <% end %>
        <div class="card-product">
          <div class=card-price>
            <h5>£<%= workspace.price %></h5>
            <p>hr</p>
          </div>
          <h2 class="workspace-name"><%= workspace.name %></h2>
          <div class= "card-icons">
            <!-- non static amenities here -->
            <% workspace.amenities.each do |amenity| %>
              <%= amenity_icon(amenity.name) %>
            <% end  %>
          </div>
          <div class="icon-postcode">
            <%= fa_icon "map-marker-alt" %>
            <div class="address-text">
              <div>
                <p><%= workspace.city %>, <%= workspace.postcode %></p>
                </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
   <div class="workspaces-rightside">
    <div id="map"
     style="width: 100%; height: 100vh"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
 </div>
</div>

app/views/workspaces/new.html.erb
<div class="container" style="width: 500px">
  <div class="form-container">
    <h2>Host a space</h2>
    <div class="form-inputs">
      <%= simple_form_for @workspace, html: {id: 'create-form'} do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :first_line_address %>
        <%= f.input :city %>
        <%= f.input :postcode %>
        <%= f.association :amenities,
                                  collection: Amenity.all, as: :check_boxes,
                                  wrapper: :vertical_collection_inline,
                                  input_html: { class: "tag-selector" },
                                  item_wrapper_class: 'tag-item'%>
        <%= f.input :photos, as: :file, input_html: { multiple: true }%>
        <%=f.check_box :terms_of_service, id:"tos_check", required: true %> <p>By ticking this box I agree to the terms and conditions<p>
      <div class="form-actions">
        <%= f.submit "Create Workspace", onclick: "checkTerms();", class: "btn btn-warning", id: "tos_btn" %>
        <%= link_to 'Back', workspaces_path, class: "btn btn-info"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/workspaces/show.html.erb
<div class="container">
  <div class="top-container">
    <div class="top-leftside">
        <div class="large-image">
          <% if @workspace.photos.attached? %>
            <%= cl_image_tag @workspace.photos.first.key, id:"img-large" %>
          <% else %>
            <%= image_tag 'placeholder01.jpg', id:"img-large", class:"img-zoom-container" %>
          <% end %>
          <div class="workspace-show-icons">
            <div class="host-avatar">
              <% if @workspace.user.photo.attached? %>
                <%= image_tag @workspace.user.photo %>
              <% end %>
            </div>
          <% unless current_user == @workspace.user %>
          <div class="workspace-fave">
            <% if Favorite.where(workspace: @workspace, user: current_user).exists? %>
              <%= link_to workspace_favorite_path(@workspace), class: "fav-a-pnk", method: :delete do %>
                <p id="favourite"><%= fa_icon "heart" %> Favourited!</p>
              <% end %>
            <% else %>
              <%= link_to workspace_favorites_path(@workspace), class: "fav-a-pnk", method: :post do %>
                <p id="favourite"><%= fa_icon "heart" %> Save to favourites</p>
              <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="top-rightside">
      <div class="small-images">
        <% if @workspace.photos.attached? %>
          <% @workspace.photos.last(2).each_with_index do |photo, index| %>
            <%= cl_image_tag photo.key, class:"bottom-image img-small", id:"right-#{index}" %>
          <% end %>
        <% else %>
          <%= image_tag 'placeholder02.jpg', class:"bottom-image img-small", id:"right-0" %>
          <%= image_tag 'placeholder03.jpg', class:"bottom-image img-small", id:"right-1" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="second-container">
    <div class="leftside">
     <div class="info">
        <div class="workspace-info">
          <h2> <%= @workspace.name %> </h2>
          <p> <%= @workspace.city %> <%= @workspace.postcode %> </p>
          <p> <% @workspace.average.floor.times do  %>
            <%= fa_icon "star", class: "fa" %>
          <% end %></p>
        </div>
        <div class="price-text" data-rate="<%= @workspace.price %>" id="price">
            <p>£<%= @workspace.price %></p>
            <p id="hour">hr</p>
        </div>
      </div>
      <div class="tabs">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Overview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-host-tab" data-toggle="pill" href="#pills-host" role="tab" aria-controls="pills-host" aria-selected="false">About the host</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-review-tab" data-toggle="pill" href="#pills-review" role="tab" aria-controls="pills-review" aria-selected="false">Reviews</a>
          </li>
        </ul>
          <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
              <h4>About the space</h4>
                <p><%= @workspace.description %></p>
                <h4>Amenities</h4>
              <div class="list-amenities">
                <% @workspace.amenities.each do |amenity| %>
                 <ul class="tab-icons"><%= amenity_icon(amenity.name) %> <%= amenity.name %></ul>
                <% end %>
                </div>
              </div>
            <div class="tab-pane fade" id="pills-host" role="tabpanel" aria-labelledby="pills-host-tab">
              <h4>Host name</h4>
               <p><%= @workspace.user.first_name %> <%= @workspace.user.last_name %></p>
              <h4>About your host</h4>
               <p><%= @workspace.user.about %></p>
            </div>
            <div class="tab-pane fade" id="pills-review" role="tabpanel" aria-labelledby="pills-review-tab">
              <% @workspace.reviews.each do |review| %>
                <li class="list-group-item">
                  <% review.rating.to_i.times do %>
                  <%= fa_icon "star", class: "fa" %>
                  <% end %>
                  <%= review.content %><br>
                  <i><%= review.user.username%> - <%= review.created_at.strftime("%A, %b %d") %></i>
                  <% end %>
                </li>
            </div>
          </div>
      </div>
      <div class="show-buttons">
          <%= link_to 'Leave a review', new_workspace_review_path(@workspace), class: "btn-edit btn btn-warning "%>
          <% if current_user == @workspace.user %>
          <%= link_to 'Edit', edit_workspace_path(@workspace), class: "btn-edit btn btn-warning"%>
          <% end %>
          <%= link_to 'More Workspaces', workspaces_path(@workspaces), class: "btn-edit btn btn-warning"%>
      </div>
    </div>
    <% if current_user != @workspace.user %>
    <%= render "shared/booking_form" %>
    <% end %>
  </div>
  <div id="map"
    style="width: 100%; height: 400px"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>