config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'business', to: 'pages#business'
  get 'hosts', to: 'pages#hosts'
  get 'membership', to: 'pages#membership'
  get 'privacy', to: 'pages#privacy'
  get 'support', to: 'pages#support'
  get 'guidelines', to: 'pages#guidelines'
  get 'terms', to: 'pages#terms'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index] do
    member do
      post :accept
      post :reject
    end
  end

  resources :workspaces do
    resources :bookings, only: [:new, :create, :edit, :update]
    resources :favorites, only: [:index, :create, :destroy]
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :terms_of_service, acceptance: true

  belongs_to :user
  belongs_to :workspace
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    bookings = Booking.all
    @user_bookings = bookings.select { |booking| booking.user_id == current_user.id && booking.confirmed }
    @workspace = Workspace.where(user_id: current_user.id)
    @workspace_bookings = bookings.select { |booking| booking.workspace.user == current_user }
  end

  def new
    @booking = Booking.new(booking_params)
    @workspace.booking = Workspace.find(params[:workspace_id])
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @workspace = Workspace.find(params[:workspace_id])
    @booking = Booking.find(params[:id])
  end

  def create
    @workspace = Workspace.find(params[:workspace_id])
    @booking = Booking.new(booking_params)
    @booking.workspace = @workspace
    @booking.user = current_user
    if @booking.save!
      redirect_to user_path(@booking.user)
    else
      render "workspaces/show"
    end
  end

  def update
    @workspace = Workspace.find(params[:workspace_id])
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      @booking.confirmed = false
      @booking.save
      redirect_to workspace_booking_path(@workspace, @booking)
    else
      render :edit
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.toggle!(:confirmed)
    redirect_to bookings_path(@booking.user)
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.toggle!(:confirmed)
    redirect_to bookings_path(@booking.user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :person_count, :price)
  end
end

app/views/bookings/_host_bookings.html.erb
<% unless @workspace.empty? %>
  <% @workspace_bookings.each do |booking| %>
  <div class="host-bookings">
    <p><%= booking.user.first_name %> <%= booking.user.last_name %>
      <%= booking.start_time.strftime("%d/%m/%y %H:%M") %></p>
      <% if booking.confirmed %>
        <p>Booking confirmed</p>
        <%= link_to "Cancel booking", reject_booking_path(booking), method: :post, class: "btn btn-sm btn-warning" %>
      <% elsif booking.confirmed == nil%>
        <%= link_to "Accept booking", accept_booking_path(booking), method: :post, class: "btn btn-sm btn-warning" %>
        <%= link_to "Reject booking", reject_booking_path(booking), method: :post, class: "btn btn-sm btn-warning" %>
      <% else %>
        <p>Booking rejected</p>
        <%= link_to "Accept booking", accept_booking_path(booking), method: :post, class: "btn btn-sm btn-warning" %>
    <% end %>
    <%= link_to "Contact Customer", root_path, class: "btn btn-sm btn-warning" %>
  </div>
  <% end %>
<% end %>

app/views/bookings/edit.html.erb
<div class="container" style="width: 500px">
  <div class="form-container">
    <h2>Edit your Booking</h2>
      <div style="display: flex">
        <h3><%= @booking.workspace.name %></h3>
        <h4><%= @booking.workspace.first_line_address %>, <%= @booking.workspace.postcode %></h4>
      </div>
      <div class="form-inputs">
        <%= simple_form_for [@workspace, @booking] do |f| %>
          <%= f.input :person_count %>
          <%= f.input :start_time %>
          <%= f.input :end_time %>
      </br>
        <div class="form-actions">
          <%= f.submit "Update booking", class: "btn btn btn-warning"%>
        </div>
      </div>
      <% end %>
      <div class="form-links">
        <%= link_to 'Back',  user_path(current_user) %>
        <div>
          <%=link_to workspace_path, method: :delete, data: { confirm: "Are you sure you want to cancel this booking?" } do %>
          <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container" style="background-color: white">
  <div class="host-property">
    <div class="property-details-left">
      <h2>Property Details</h2>
      <% @workspace.each do |workspace| %>
        <div class="property-detail"><p>Name</p>
          <p><%= workspace.name %></p>
        </div>
        <div class="property-detail"><p>Address</p>
          <p><%= workspace.first_line_address %> <%= workspace.city %> <%= workspace.postcode %></p>
        </div>
        <div class="property-detail"><p>Description</p>
          <p><%= workspace.description %> </p>
        </div>
        <%= link_to 'Edit', edit_workspace_path(@workspace), class: "btn btn-warning btn-host"%>
      <% end %>
    </div>
    <div class="property-calendar-right">
      <!-- <h2 style="text-align: center">Calendar here</h2> -->
    </div>
  </div>
  <div class="pb-2">
    <div class="host-bookings-card">
      <h2>My Bookings</h2>
      <% if @workspace_bookings.empty? %>
        <p>No Bookings yet</p>
      <% else %>
        <%= render "host_bookings" %>
      <% end %>
    </div>
  </div>
</div>