config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'business', to: 'pages#business'
  get 'hosts', to: 'pages#hosts'
  get 'membership', to: 'pages#membership'
  get 'privacy', to: 'pages#privacy'
  get 'support', to: 'pages#support'
  get 'guidelines', to: 'pages#guidelines'
  get 'terms', to: 'pages#terms'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index] do
    member do
      post :accept
      post :reject
    end
  end

  resources :workspaces do
    resources :bookings, only: [:new, :create, :edit, :update]
    resources :favorites, only: [:index, :create, :destroy]
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :terms_of_service, acceptance: true

  has_many :workspaces
  has_many :bookings, dependent: :destroy
  has_many :reviews
  has_many :favorites
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bookings = @user.bookings
    @favorites = Favorite.where(user_id: current_user.id)
  end
end

app/views/users/_booking.html.erb
<div class="booking-card">
  <% @bookings.each do |booking| %>
  <%= link_to workspace_path(booking.workspace), class: "workspace-link" do %>
    <div class="workspace-card">
      <% if booking.workspace.photos.attached? %>
          <%= cl_image_tag booking.workspace.photos.first.key %>
        <% else %>
          <%= image_tag 'placeholder01.jpg' %>
        <% end %>
      <h3 class="booking-name"><%= booking.workspace.name %></h3>
        <div class="booking-details">
          <p><%= booking.start_time.strftime('%a %e %B %l:%M')%> -
              <%= booking.end_time.strftime('%a %e %B %l:%M')%></p>
          <p><%= booking.person_count %>
          <% if booking.person_count > 1%>
            guests</p>
          <% else %>
            guest</p>
          <% end %>
        </div>
        <div class="links">
          <%= link_to "Get in touch", '#', class: "booking-button" %>
          <% if booking.confirmed && booking.start_time < Date.today %>
            <%= link_to 'Leave a Review', new_workspace_review_path(booking.workspace), class: "booking-button" %>
          <% elsif booking.confirmed %>
            <h4>Confirmed</h4>
          <% elsif booking.confirmed == nil %>
            <h4>Pending confirmation</h4>
            <%= link_to 'Edit', edit_workspace_booking_path(booking.workspace, booking), class: "booking-button" %>
          <% else %>
            <h4>Booking rejected</h4>
          <% end %>
        </div>
      <div class="address">
        <i class="fas fa-map-marker-alt"></i><h4><%= booking.workspace.first_line_address %> <%= booking.workspace.city %> <%= booking.workspace.postcode %></h4>
      </div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/users/_favourites.html.erb
<div class="booking-card">
  <% @favorites.each do |favorite| %>
    <div class="workspace-card">
      <% if favorite.workspace.photos.attached? %>
            <%= cl_image_tag favorite.workspace.photos.first.key %>
          <% else %>
            <%= image_tag 'placeholder01.jpg'%>
          <% end %>
      <h3 class="booking-name"><%= favorite.workspace.name %></h3>
      <div class="links">
        <%= link_to "See workspace", workspace_path(favorite.workspace), class: "booking-button"%>
      </div>
      <div class="address">
       <%= fa_icon "map" %><h4><%= favorite.workspace.city %> </h4>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="account" style="background-color: white">
  <div class="top-account">
    <div class="top-left">
      <% if current_user.photo.attached? %>
      <%= cl_image_tag(@user.photo.key, class: "avatar-large") %>
      <% else %>
        <%= fa_icon "user", class: "fa-8x" %>
      <% end %>
      <div class="profile-link"><%= link_to "Edit Profile", edit_user_registration_path %></div>
      <div class="property-link">
        <% if current_user.workspaces != [] %>
      <%= link_to "Manage Property", bookings_path %>
      <% else %>
      <%= link_to "Become a host", new_workspace_path %>
      <% end %>
      </div>
    </div>
  </div>
    <div class="top-right">
      <h2>Hi I'm <%= @user.first_name %>!</h2>
      <h3>About Me</h3>
      <p> <%= @user.about %></p>
    </div>
  </div>
  <div class="bottom">
    <div id="account-tab">
      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-bookings-tab" data-toggle="pill" href="#pills-bookings" role="tab" aria-controls="pills-bookings" aria-selected="true">Bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-reviews-tab" data-toggle="pill" href="#pills-reviews" role="tab" aria-controls="pills-reviews" aria-selected="false">Reviews</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-favourites-tab" data-toggle="pill" href="#pills-favourites" role="tab" aria-controls="pills-favourites" aria-selected="false">Favourites</a>
        </li>
      </ul>
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-bookings" role="tabpanel" aria-labelledby="pills-bookings-tab">
            <%= render "booking" %>
          </div>
          <div class="tab-pane fade" id="pills-reviews" role="tabpanel" aria-labelledby="pills-reviews-tab">
          </div>
          <div class="tab-pane fade" id="pills-favourites" role="tabpanel" aria-labelledby="pills-favourites-tab">
            <%= render "favourites" %>
          </div>
        </div>
      </div>
    </div>
</div>