config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'business', to: 'pages#business'
  get 'hosts', to: 'pages#hosts'
  get 'membership', to: 'pages#membership'
  get 'privacy', to: 'pages#privacy'
  get 'support', to: 'pages#support'
  get 'guidelines', to: 'pages#guidelines'
  get 'terms', to: 'pages#terms'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:index] do
    member do
      post :accept
      post :reject
    end
  end

  resources :workspaces do
    resources :bookings, only: [:new, :create, :edit, :update]
    resources :favorites, only: [:index, :create, :destroy]
    resources :reviews, only: [:new, :create, :edit]
  end

  resources :users, only: [:show, :edit, :update]
end

app/views/shared/_booking_form.html.erb
<div class= "rightside">
  <div class= "bookingform">
    <h3>Reserve this space</h3>
    <%= simple_form_for [@workspace, Booking.new] do |f| %>
      <%= f.input :person_count %>
      <%= f.input :start_time, as: :string %>
      <%= f.input :end_time, as: :string %>
      <%=f.check_box :terms_of_service, required: true %> By ticking this box I agree to the terms and conditions
      </br>
    <div class="price-target" data-rate="<%= @workspace.price %>" id="total-price">
      Total: £0
    </div>
      <%= f.submit "", class: "btn btn-warning", id:"book-now", class: "hidden" %>
      <button id="sweet-alert-demo" class="btn btn-warning">Book Now!</button>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= fa_icon("instagram", type: :brand) %>
    <%= fa_icon("facebook", type: :brand) %>
    <%= fa_icon("twitter", type: :brand) %>
    <%= fa_icon("linkedin", type: :brand) %>
    <%= link_to "Privacy Policy", privacy_path %>
    <%= link_to "Terms and Conditions", terms_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Support", support_path %>
    <%= link_to "Community Guidelines", guidelines_path %>
  </div>
  <div class="footer-copyright">
   <%= fa_icon "copyright" %> MyPlace Workspace
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
   <div class="logo", class="navbar-brand">
     <%= image_tag '1.png' %>
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to root_path do %>
          <%= fa_icon "home 2x", class: "nav-link" %>
          <% end %>
        </li>
        <div class="text-link">
          <li class="nav-item">
            <%= link_to "Host your space", new_workspace_path, class: "nav-link host-link" %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link log-out" %>
          </li>
        </div>
        <li class="nav-item dropdown">
          <%= fa_icon "bars 2x", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Account", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "For hosts", hosts_path, class: "dropdown-item" %>
            <%= link_to "For businesses", business_path, class: "dropdown-item" %>
            <%= link_to "About", about_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <li class="nav-item active">
          <%= link_to root_path do %>
          <%= fa_icon "home 2x", class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <li class="nav-item">
          <%= link_to "Host your space", new_workspace_path, class: "nav-link host-link" %>
        </li>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= fa_icon "bars 2x", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Account", "#", class: "dropdown-item" %>
            <%= link_to "For hosts", hosts_path, class: "dropdown-item" %>
            <%= link_to "For businesses", business_path, class: "dropdown-item" %>
            <%= link_to "About", about_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>